version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:21.0.2

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      - run: gradle dependencies
      - run: gradle test
workflows:
  gradle-build:
    jobs:
      - build